// import styles from "./style-custom.json";
const styles = require("./style-custom.json");
module.exports = {
	mode: "jit",
	purge: ["./pages/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
	darkMode: "class", // or 'media' or 'class'

	theme: {
		extend: {
			fontFamily: {
				sans: ["SF Pro Text", "sans-serif"],
				// sans: ["SF Pro Display", "sans-serif"],
				ProDisplay: ["SF Pro Display", "sans-serif"],
			},
			colors: {
				primary_6: styles.primary_6.background,
				primary_3: styles.primary_3.background,
				primary_8: styles.primary_8.background,
				primary_10: styles.primary_10.background,
				primary_12: styles.primary_12.background,
				yellow_2: styles.yellow_2.color,
				yellow_3: styles.yellow_3.color,
				gray_1: styles.gray_1.background,
				gray_2: styles.gray_2.background,
				gray_8: styles.gray_8.background,
				gray_12: styles.gray_12.background,
				gray_4: styles.gray_4.background,
				gray_11: styles.gray_11.background,
				"gray-1": styles.gray_1.background,
				"gray-2": styles.gray_2.background,
				"gray-3": styles.gray_3.background,
				orange_3: styles.orange_3.color,
				orange_6: styles.orange_6.color,
				orange_9: styles.orange_9.color,
				red_6: styles.red_6.color,
				red_6_1: styles.red_6_1.color,
				red_6_2: styles.red_6_2.color,
				dark_medium: styles.dark_medium.color,
				dark: styles.dark.color,
				purple: styles.purple.color,
				green: styles.green.color,
				blue: styles.blue.color,
				pink: styles.pink.color,
			},
			fontSize: {
				"size-15": styles.font_15["font-size"],
				smallest: styles.font_smallest["font-size"],
				"1xl": styles.font_1xl["font-size"],
				base_2: styles.font_base_2["font-size"],
				1: styles.font_1["font-size"],
				2: styles.font_2["font-size"],
				3: styles.font_3["font-size"],
				3: styles.font_3["font-size"],
				4: styles.font_4["font-size"],
				5: styles.font_5["font-size"],
				6: styles.font_6["font-size"],
				7: styles.font_7["font-size"],
				8: styles.font_8["font-size"],
			},
			lineHeight: {
				11: styles.leading_11["line-height"],
				12: styles.leading_12["line-height"],
				13: styles.leading_13["line-height"],
				14: styles.leading_14["line-height"],
				15: styles.leading_15["line-height"],
				16: styles.leading_16["line-height"],
				17: styles.leading_17["line-height"],
				18: styles.leading_18["line-height"],
				19: styles.leading_19["line-height"],
				20: styles.leading_20["line-height"],
				21: styles.leading_21["line-height"],
			},
			textColor: {
				"gray-1": styles.text_gray_1["color"],
			},
			width: {
				"64-25": styles.w_64_25["width"],
				"25/6": styles.w_25_6["width"],
				"25/9": styles.w_25_9["width"],
				"50/8": styles.w_50_8["width"],
				4.5: styles.w_4_5["width"],
				120: styles.w_120["width"],
				"1/60": styles.w_1_60["width"],
				"1/84": styles.w_1_84["width"],
				73: styles.w_73["width"],
				"33/8": styles.w_33_8["width"],
				108: styles.w_108["width"],
				"minus-128": "calc(100%  - 512px)",
				128: "512px",
				"100-32": "calc(100% - 32px)",
			},
			height: {
				"nav-mobile": "var(--h-nav-mobile)",
				"64-25": styles.h_64_25["height"],
				85: styles.h_85["height"],
				134: styles.h_134["height"],
				"150-68-85": "calc(100vh - 145px - 68px - 85px)",
				"68-85": "calc(100vh - 68px - 85px)",
				68: "calc(100% - 68px)",
			},
			borderWidth: {
				1: styles.border_1["border-width"],
			},
			letterSpacing: {
				1: styles.tracking_1["letter-spacing"],
				2: styles.tracking_2["letter-spacing"],
				3: styles.tracking_3["letter-spacing"],
				4: styles.tracking_4["letter-spacing"],
				5: styles.tracking_5["letter-spacing"],
				6: styles.tracking_6["letter-spacing"],
				7: styles.tracking_7["letter-spacing"],
				8: styles.tracking_8["letter-spacing"],
				9: styles.tracking_9["letter-spacing"],
				10: styles.tracking_10["letter-spacing"],
			},
			backgroundOpacity: {
				8: "0.08",
			},
			borderColor: {
				"gray-1": "#E8E8EA",
			},
			maxWidth: {
				1: "18rem",
				2: "7rem",
				"1/4": "25%",
				"1/2": "50%",
				"3/4": "75%",
				2.5: "2.5rem",
			},
			maxHeight: {
				"24-5": "392px",
			},
			minHeight: {
				"24-5": "392px",
			},
			padding: {
				15: "60px",
				17: "68px",
				4.5: "18px",
			},
			zIndex: {
				1: "1",
			},
			inset: {
				85: "85px",
			},
		},
	},
	variants: {
		extend: {
			borderWidth: ["last"],
		},
	},
	plugins: [require("@tailwindcss/line-clamp")],
};
